local STRINGS = GLOBAL.STRINGS

---WAR!---
STRINGS.NAMES.CONCHEROR = "Concheror"
STRINGS.RECIPE_DESC.CONCHEROR = "Health and speeed in box form."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CONCHEROR = "Looks very Far-Eastern."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CONCHEROR = "Who would wear this?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CONCHEROR = "Is wood box."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CONCHEROR = "I wish this box was bigger, so I could lock myself in there."
STRINGS.CHARACTERS.WX78.DESCRIBE.CONCHEROR = "WOODEN PORTABLE STORAGE DEVICE"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CONCHEROR = "It's a wooden storage device, made to be worn on one's back."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CONCHEROR = "Oh, I really like this backpack!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CONCHEROR = "There are better materials to make a backpack with."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CONCHEROR = "A bit bulky, but it's a backpack nonetheless."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CONCHEROR = "We'd like to store our toys in it."

-- WAR! --

STRINGS.NAMES.QUICKIEBOMBLAUNCHER = "Quickiebomb Launcher"
STRINGS.RECIPE_DESC.QUICKIEBOMBLAUNCHER = "Deploys bombs quickly."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUICKIEBOMBLAUNCHER = "A tool for deploying bombs."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.QUICKIEBOMBLAUNCHER = "It looks boring... And kind of dangerous."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.QUICKIEBOMBLAUNCHER = "Ka-boom!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.QUICKIEBOMBLAUNCHER = "Blow them up and watch their gibs fly."
STRINGS.CHARACTERS.WX78.DESCRIBE.QUICKIEBOMBLAUNCHER = "IT STORES EXPLOSIVES"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.QUICKIEBOMBLAUNCHER = "Weapon made of metal. Smells of brimstone."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.QUICKIEBOMBLAUNCHER = "Could work on trees."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.QUICKIEBOMBLAUNCHER = "Huh, that's a new one."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.QUICKIEBOMBLAUNCHER = "Small explosions are hidden inside!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.QUICKIEBOMBLAUNCHER = "We should be careful around this."

---

STRINGS.NAMES.QUICKIEBOMB = "Quickie Bomb"
STRINGS.RECIPE_DESC.QUICKIEBOMB = "Use it quickly."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUICKIEBOMB = "It's spiky... and sticky!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.QUICKIEBOMB = "At least its color is pretty."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.QUICKIEBOMB = "Puny little bomb."
STRINGS.CHARACTERS.WENDY.DESCRIBE.QUICKIEBOMB = "Its spikes remind me of... pain."
STRINGS.CHARACTERS.WX78.DESCRIBE.QUICKIEBOMB = "DEMOLITION DEVICE"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.QUICKIEBOMB = "Explosive ball with sharp, sticky edges."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.QUICKIEBOMB = "Could work on trees, I guess?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.QUICKIEBOMB = "Short-lived, but intimidating."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.QUICKIEBOMB = "Explosion encased in tiny, but respectable armor!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.QUICKIEBOMB = "We should be extra careful around this."

---

STRINGS.NAMES.QUICKIEBOMB_CRIT = "Crit Quickie Bomb"
STRINGS.RECIPE_DESC.QUICKIEBOMB_CRIT = "Use it quickly."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUICKIEBOMB_CRIT = "It's glowy and red."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.QUICKIEBOMB_CRIT = "It glows almost like fire!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.QUICKIEBOMB_CRIT = "Little bomb is scary!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.QUICKIEBOMB_CRIT = "It's filled with raw urge to kill things."
STRINGS.CHARACTERS.WX78.DESCRIBE.QUICKIEBOMB_CRIT = "IT'S OVERCHARGED"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.QUICKIEBOMB_CRIT = "This explosive ball appears to be charged with electricity."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.QUICKIEBOMB_CRIT = "It's pretty deadly now, eh?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.QUICKIEBOMB_CRIT = "Oh, this one is extra intimidating."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.QUICKIEBOMB_CRIT = "Small bomb bursts with rage!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.QUICKIEBOMB_CRIT = "We don't want to play with that ball."

---

STRINGS.NAMES.ULLAPOOL_CABER = "Ullapool Caber"
STRINGS.RECIPE_DESC.ULLAPOOL_CABER = "Ka-blooie!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "It's a hand grenade.",
	DUD = "It's broken.",
}
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "Throwable explosions? Me like!",
	DUD = "It's good for nothing. Well, maybe as fire fuel...",
}
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "Is boom grenade bomb.",
	DUD = "Bomb have hole in head.",
}
STRINGS.CHARACTERS.WENDY.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "After a single explosion it will be done for good.",
	DUD = "Broken, just like my heart.",
}
STRINGS.CHARACTERS.WX78.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "RANGED EXPLOSIVE WEAPONRY",
	DUD = "EXPLOSIONS LEFT: ZERO",
}
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "It's a common explosive weapon.",
	DUD = "Leftovers of a grenade.",
}
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "It could help doing some work.",
	DUD = "It broke, eh?",
}
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "An explosive stick, how... bombastic.",
	DUD = "At least it's burnable.",
}
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "Fit for a fearless kamikaze attack!",
	DUD = "It's good for nothing.",
}
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "Will it drop confetti after the explosion?",
	DUD = "It's empty in there.",
}
---

STRINGS.NAMES.TF2BOUNTYHAT = "Bounty Hat"
STRINGS.RECIPE_DESC.TF2BOUNTYHAT = "Extra storage for some extra scrumpy."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TF2BOUNTYHAT = "It's a portable chest."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TF2BOUNTYHAT = "Kinda like a pirate hat."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TF2BOUNTYHAT = "Is box for head."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TF2BOUNTYHAT = "If I put enough rocks in it and start jumping..."
STRINGS.CHARACTERS.WX78.DESCRIBE.TF2BOUNTYHAT = "HEAD-COMPATIBLE INVENTORY EXTENSION"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TF2BOUNTYHAT = "A black hat with a wooden chest attached to it."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TF2BOUNTYHAT = "As long as that chest is wooden, I like it."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TF2BOUNTYHAT = "This looks just plain dumb."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TF2BOUNTYHAT = "Shoo, this won't fit my costume at all!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TF2BOUNTYHAT = "Can we put a hat on that chest?"

---

STRINGS.NAMES.EQUALIZER = "Equalizer"
STRINGS.RECIPE_DESC.EQUALIZER = "Deals damage equal to your pain."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.EQUALIZER = "Its name is quite scientific!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.EQUALIZER = "Its name sounds boring."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.EQUALIZER = "Is army axe for pick."
STRINGS.CHARACTERS.WENDY.DESCRIBE.EQUALIZER = "The skull that appears when you equip it. I like it."
STRINGS.CHARACTERS.WX78.DESCRIBE.EQUALIZER = "EVERYTHING HAS A PRICE"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EQUALIZER = "It's a high-quality pickaxe."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.EQUALIZER = "Not for wood."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.EQUALIZER = "Better than a regular tool."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.EQUALIZER = "Warrior's pickaxe!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.EQUALIZER = "What is it equal to?"

---

STRINGS.NAMES.BATTALIONS_BACKUP = "Battalion's Backup"
STRINGS.RECIPE_DESC.BATTALIONS_BACKUP = "Defend your own battalion."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BATTALIONS_BACKUP = "It's pretty well-equipped."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BATTALIONS_BACKUP = "What is this good for?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BATTALIONS_BACKUP = "Is very soldier back pack."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BATTALIONS_BACKUP = "Helps to extend the pain that is life."
STRINGS.CHARACTERS.WX78.DESCRIBE.BATTALIONS_BACKUP = "NO BACKUP COPY OF BATTALION FOUND"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BATTALIONS_BACKUP = "It's equipped with a compass and a map."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BATTALIONS_BACKUP = "Good thing trees can't buff themselves with this!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BATTALIONS_BACKUP = "Looks quite civilized."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BATTALIONS_BACKUP = "With this it will be easier to navigate!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BATTALIONS_BACKUP = "Backs down, backs up!"

for k,v in pairs(GLOBAL.ModManager.mods) do
if v.modinfo and v.modinfo.name == "Soldier (TF2)" then
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.CONCHEROR = "Suz-Tzu would be proud."
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.QUICKIEBOMBLAUNCHER = "This is what those filthy Englishmen hide under their dress."
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.QUICKIEBOMB = "You call that fast? My bullets run faster!"
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.QUICKIEBOMB_CRIT = "At least it's still RED!"
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "This, for one, I like.",
	DUD = "American grenades never break!",
}
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.TF2BOUNTYHAT = "This is not an American hat!"
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.EQUALIZER = "I will show you who is the Soldier here!"
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.BATTALIONS_BACKUP = "That's a proper American backpack."

STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.HALF_ZATOICHI = "A sword of that english cross-dresser."
STRINGS.CHARACTERS.TF2SOLDIER.ANNOUNCE_HONORBOUND = "Don't even think about it before killing something!"
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.TF2SAMURAIARMOR = "I don't want that armor! I REFUSE to wear that armor!"
STRINGS.CHARACTERS.TF2SOLDIER.DESCRIBE.TF2SAMURAIHAT = "It's that scottish cyclops's helmet!"
end
end

for k,v in pairs(GLOBAL.ModManager.mods) do
if v.modinfo and v.modinfo.name == "Demoman" then
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.CONCHEROR = "What is this, a bloody box?"
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.QUICKIEBOMBLAUNCHER = "Ha, one of me favorites!"
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.QUICKIEBOMB = "Me short-lived bomb, but how deadly."
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.QUICKIEBOMB_CRIT = "Bloody fair and balanced, ha-ha!"
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.ULLAPOOL_CABER = 
{
	GENERIC = "Oh, I'm gonna blast ya into thin gruel...",
	DUD = "I'm gonna lick ya...",
}
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.TF2BOUNTYHAT = "Bloody perfect!"
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.EQUALIZER = "I saw wee lads playing with something like this in sandbox."
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.BATTALIONS_BACKUP = "Back up lad, back up."

STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.HALF_ZATOICHI = "Me bloody sword that likes him some blood."
STRINGS.CHARACTERS.DEMOMAN.ANNOUNCE_HONORBOUND = "Blood, it needs more bloody blood!"
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.TF2SAMURAIARMOR = "Oh, bloody epic!"
STRINGS.CHARACTERS.DEMOMAN.DESCRIBE.TF2SAMURAIHAT = "Bloody brilliant!"
end
end

--WAR! END

STRINGS.NAMES.HALF_ZATOICHI = "Half-Zatoichi"
STRINGS.RECIPE_DESC.HALF_ZATOICHI = "A blood-hungry weapon."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HALF_ZATOICHI = "It's a cursed blade. Spooky!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.HALF_ZATOICHI = "It's a big knife."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HALF_ZATOICHI = "Is sharp! Is strong!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.HALF_ZATOICHI = "Looks sharp enough to end a life in one swing."
STRINGS.CHARACTERS.WX78.DESCRIBE.HALF_ZATOICHI = "THIS SWORD IS HIDING SOMETHING"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HALF_ZATOICHI = "A sword. Putting it down before a kill is considered humiliating."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.HALF_ZATOICHI = "It has this eerie feeling about it..."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HALF_ZATOICHI = "Oh, it's one of these. Can't put it down before a kill."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HALF_ZATOICHI = "Ah, a truly honourable blade."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.HALF_ZATOICHI = "We always wanted to be a knight!"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_HONORBOUND = "I... can't put it down until it's covered in blood!"
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_HONORBOUND = "I'm not putting this away before it's all bloody."
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_HONORBOUND = "Sword wants Wolfgang to crush enemy first!"
STRINGS.CHARACTERS.WENDY.ANNOUNCE_HONORBOUND = "I should end some lives with it first."
STRINGS.CHARACTERS.WX78.ANNOUNCE_HONORBOUND = "ACTION DENIED: FLESHLING BLOOD REQUIRED"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_HONORBOUND = "This blade needs to be covered in blood."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_HONORBOUND = "Needs more blood, eh?"
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_HONORBOUND = "It needs to be dirtied by blood."
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_HONORBOUND = "I can't let this honourable blade down like that!"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_HONORBOUND = "We can't do that. Not before it's covered in blood."

STRINGS.NAMES.TF2SAMURAIARMOR = "Bushi-Dou"
STRINGS.RECIPE_DESC.TF2SAMURAIARMOR = "Aerodynamical armor."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TF2SAMURAIARMOR = "Its surface is quite shiny."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TF2SAMURAIARMOR = "At least it can still burn."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TF2SAMURAIARMOR = "Is make move faster!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TF2SAMURAIARMOR = "It's dark, like my thoughts."
STRINGS.CHARACTERS.WX78.DESCRIBE.TF2SAMURAIARMOR = "AERODYNAMIC DESIGN"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TF2SAMURAIARMOR = "A piece of armour made in a such way that it accelerates movement."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TF2SAMURAIARMOR = "It's made of burnt wood. It's okay, I guess."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TF2SAMURAIARMOR = "Nicely designed."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TF2SAMURAIARMOR = "A light armour for fast battles!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TF2SAMURAIARMOR = "It feels like it doesn't have any weight."

STRINGS.NAMES.TF2SAMURAIHAT = "Samur-Eye"
STRINGS.RECIPE_DESC.TF2SAMURAIHAT = "Light head protection."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TF2SAMURAIHAT = "It's a very stylized helmet."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TF2SAMURAIHAT = "At least it can still burn."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TF2SAMURAIHAT = "Is make move faster!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TF2SAMURAIHAT = "It's dark, like my thoughts."
STRINGS.CHARACTERS.WX78.DESCRIBE.TF2SAMURAIHAT = "AERODYNAMIC DESIGN"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TF2SAMURAIHAT = "A piece of armour made in a such way that it accelerates movement."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TF2SAMURAIHAT = "It's made of burnt wood. It's okay, I guess."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TF2SAMURAIHAT = "Nicely designed."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TF2SAMURAIHAT = "A light armour for fast battles!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TF2SAMURAIHAT = "It feels like it doesn't have any weight."
